name: 'Github secrets to dotenv file'
description: 'Generate dotenv file with all secrets setted in github secrets'
inputs:
  secrets:
    description: 'JSON (as string) from secrets'
    required: true
    default: ''  
outputs:
  filePath:
    description: 'Path to dotenv file'
runs:
  using: 'node12'
  main: 'index.js'