name: Testing action

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set Github Secrets as Env variables
              id: myAction
              uses: felippechemello/github-secrets-to-dotenv@0.1.0
              with:
                  secrets: ${{ toJson(secrets) }}

            - name: print secret
              run: cat ${{ steps.myAction.outputs.filePath }}

